### PR TITLE
adds uniq helper

### PR DESCRIPTION
**Pull request by zigahertz**
I thought this would be helpful to have, I needed it in one of the projects I'm working on.

### CODE REVIEW

**Comment by martndemus** [comment]
@zigahertz Uniq is an alias for `union`, we already have that helper. 

Maybe add an alias here too? Thoughts @poteto?

**Comment by poteto** [comment]
I think I would prefer to have one helper, but to update the README so that people looking for `uniq` will be pointed to use `union` instead.

**Comment by zigahertz** [comment]
@martndemus @poteto thanks! I didn't realize that `union` had this functionality for a single array. I can submit a PR that updates the README for this purpose.

**Comment by martndemus** [comment]
Yes please!

**Comment by zigahertz** [comment]
alright, I've done so at https://github.com/DockYard/ember-composable-helpers/pull/113. Closing this PR.

**Pull request closed without merging**
