### PR TITLE
Use "New Module Imports"

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/ember-cli/ember-rfc176-data

/cc @cibernox

### CODE REVIEW

**Comment by cibernox** [comment]
It looks good but there is still imports using the old shims we have to fix. Does the codemod support those?

**Comment by Turbo87** [comment]
> It looks good but there is still imports using the old shims we have to fix.

looks like I missed those 🙈 

> Does the codemod support those?

no, but the `no-old-shims` ESLint rule does

**Comment by Turbo87** [comment]
> It looks good but there is still imports using the old shims we have to fix

done :)

**Comment by cibernox** [comment]
New shims all-the-things!

**Pull request merged**
