### PR TITLE
Tree shake helpers using `only` or `except`

### LINKED ISSUE #29: Tree shake unused helpers

### PR DESCRIPTION
**Pull request by poteto**
Closes #29

### CODE REVIEW

**Comment by poteto** [comment]
@martndemus :eyes: please

**Comment by martndemus** [comment]
LGTM, but a few things:
- can you remove the compose artifact in another PR?
- should we add tests for the tree shaking?

**Comment by martndemus** [comment]
One more thing: should we wanr on `test` or `development` that a helper has been filtered out? E.g.:

```js
export default Ember.Helper.helper(() => assert('The ${helperName} helper has been disabled, if you want to use this helper please enable it in your config file'));
```

**Comment by poteto** [comment]
I was actually unsure how to test. If I add the config to the addon's `config/environment` or `dummy/config/environment`, it will actually remove the helper and break tests...

**Comment by poteto** [comment]
If the user tries to use a helper that is excluded it will throw an error. A warning doesn't seem necessary

**Comment by martndemus** [comment]
For tests: We can use `mocha` to test on the Node.js level

For the warning: It might prevent someone losing an hour of his life because he was checking if the addon was installed correctly.

**Comment by poteto** [comment]
Tests have been added.

The excluded helper will not be included at all, so we cannot perform an assertion within the individual helper definition. 

> For the warning: It might prevent someone losing an hour of his life because he was checking if the addon was installed correctly.

I disagree with this. If the user has explicitly opted-in to whitelisting or blacklisting specific helpers, they should already be aware that not all helpers will be available. By default, all helpers are included – these white/blacklists are specifically for optimization.

Further, Ember will already throw a JavaScript error in the console when you try to use a helper that doesn't exist. A warning would be redundant.

**Comment by martndemus** [comment]
Tests look good, let's merge this!

**Comment by poteto** [comment]
@homu r+

**Pull request merged**
