### PR TITLE
Fix sort-by with a function

### PR DESCRIPTION
**Pull request by Asherlc**
Ember.computed.sort seems to require you to send in a raw function (not a key that references a function) for it to work.

### CODE REVIEW

**Comment by martndemus** [comment]
Can you add a test that fails without the fix?

**Comment by Asherlc** [comment]
This may be a silly question, but how do I run tests for an addon?

**Comment by martndemus** [comment]
`ember test` :)

**Comment by Asherlc** [comment]
Ok, at 65a9649830efe818f90daa93c03a580cdef3741f there is a test which fails with a function, but passes in 084e7503cc555289eda674bbf08b44709aaa727b

Does that do the trick?

**Comment by Asherlc** [comment]
checking in on this

**Comment by martndemus** [comment]
@Asherlc can you add a little documentation to README.md?

**Comment by Asherlc** [comment]
sure thing, done

**Comment by martndemus** [comment]
Closed via #191

**Pull request closed without merging**
