### PR TITLE
Make `pipe` helper promise aware

### LINKED ISSUE #85: Promise-aware pipe helper
- [x] Check if the return value is a Promise
- [x] Promise should yield a value in its `then` hook, which is then passed into the next func 
- [x] If the Promise rejects, we abort the entire chain

### PR DESCRIPTION
**Pull request by poteto**
Closes #85

### CODE REVIEW

**Comment by poteto** [comment]
@homu r+

**Comment by henrymazza** [comment]
If promise is rejected shouldn't it halt the chain? I'm thinking on scenarios like
```
<button {{action (pipe addToCart purchase redirectToThankYouPage) item}}>
  1-Click Buy
</button>
```
if `addToCart` returns an error (e.g. connection lost) then purchase shouldn't be hit.

**Comment by henrymazza** [comment]
`isPromise()` should test for `PromiseProxy` too.

**Comment by poteto** [comment]
Yes, it already does that. I added a test to make it more obvious – #101

**Comment by henrymazza** [comment]
Found the problem here. My function returns a PromiseProxy which gets false on `isPromise()`. Perhaps test for that too?

**Comment by poteto** [comment]
@henrymazza Good catch! Can you please open a new issue for it?

**Comment by henrymazza** [comment]
Ok. I wish I knew how to fix it, but I couldn't find how do detect the Mixin. `instanceof` doesn't work.

**Comment by henrymazza** [comment]
#102

**Pull request merged**
