### PR TITLE
Add chunk helper

### PR DESCRIPTION
**Pull request by thomascchen**
Adds chunk helper (Issue https://github.com/DockYard/ember-composable-helpers/issues/57)

### CODE REVIEW

**Comment by martndemus** [comment]
Initial work looks good to me. We need to investigate why the group-by helper is broken on beta/canary before we can merge the PR i'm afraid.

**Comment by poteto** [comment]
If you rebase this against master, `beta` will be an allowed failure.

**Comment by thomascchen** [comment]
Thanks! I rebased :+1:

**Comment by poteto** [comment]
The `array` argument should be the last, see https://github.com/DockYard/ember-composable-helpers#argument-ordering

**Comment by thomascchen** [comment]
Good call -- I reordered the arguments.

**Comment by martndemus** [comment]
@homu r+

**Pull request merged**
