### PR TITLE
slice helper

### PR DESCRIPTION
**Pull request by Asherlc**
Slices an array

### CODE REVIEW

**Comment by martndemus** [comment]
1) I'm not particularly sold on the hash param addition
2) Needs a test for when the array contents are updated, as I suspect this will not update when the content of the array updates.

**Comment by Asherlc** [comment]
1. I've removed the hash params
2. You were correct -- this has been remedied.
3. Done

**Comment by Asherlc** [comment]
Merge conflicts resolved

**Comment by poteto** [comment]
Looks like there's some overlap with the [`take`](https://github.com/DockYard/ember-composable-helpers/blob/master/app/helpers/take.js) helper, any chance you could DRY it up?

**Comment by martndemus** [comment]
Closed via #190

**Pull request closed without merging**
